kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  selfLink: /apis/build.openshift.io/v1/namespaces/trash/buildconfigs/centos8-oracle-jre
  resourceVersion: '610421'
  name: centos8-oracle-jre
  uid: 88048acd-1f56-4791-bc5e-33c8cab1b0ef
  creationTimestamp: '2020-10-25T15:53:02Z'
  managedFields:
    - manager: oc.exe
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2020-10-25T15:53:02Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:build': {}
        'f:spec':
          'f:output':
            'f:to':
              .: {}
              'f:kind': {}
              'f:name': {}
          'f:runPolicy': {}
          'f:source':
            'f:binary': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy':
              .: {}
              'f:from':
                .: {}
                'f:kind': {}
                'f:name': {}
            'f:type': {}
          'f:triggers': {}
  namespace: trash
  labels:
    build: centos8-oracle-jre
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'centos8-oracle-jre:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'centos:centos8'
  postCommit: {}
  source:
    type: Binary
    binary: {}
  triggers:
    - type: GitHub
      github:
        secret: AtVQYwHPzZNWPERY6M9-
    - type: Generic
      generic:
        secret: yc4YJJvpxx-6kyxXuUui
  runPolicy: Serial
status:
  lastVersion: 0
