kind: Deployment
apiVersion: apps/v1
metadata:
  name: processing
  namespace: default
  labels:
    app: processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processing
  template:
    metadata:
      labels:
        app: processing
    spec:
      containers:
        - name: processing
          image: 'processing:latest'
          imagePullPolicy: Never
