kind: Deployment
apiVersion: apps/v1
metadata:
    name: activemq
    namespace: amq
    labels:
        app: activemq
spec:
    replicas: 1
    selector:
        matchLabels:
            app: activemq
    template:
        metadata:
            annotations:
                sidecar.istio.io/inject: 'false'
                sidecar.istio.io/userVolumeMount: '[{"name":"my-cert", "mountPath":"/etc/my-cert", "readonly":true}]'
                sidecar.istio.io/userVolume: '[{"name":"my-cert", "secret":{"secretName":"my-cert"}}]'
            labels:
                app: activemq
        spec:
            containers:
                -   name: activemq
                    image: 'rmohr/activemq:5.15.9'
                    imagePullPolicy: IfNotPresent
                    ports:
                        -   containerPort: 61616
                        -   containerPort: 8161

---
apiVersion: v1
kind: Service
metadata:
    name: activemq-service
    namespace: amq
    labels:
        app: activemq
spec:
    type: NodePort
    selector:
        app: activemq
    ports:
        - port: 61616
          name: p1
          protocol: TCP
        - port: 8161
          name: p2
          protocol: TCP
