kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  selfLink: /apis/build.openshift.io/v1/namespaces/trash/buildconfigs/processing
  resourceVersion: '932518'
  name: processing
  uid: 1b175c25-6103-49e6-98f4-56a4690b9c68
  creationTimestamp: '2021-08-15T11:23:19Z'
  managedFields:
    - manager: oc.exe
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2021-08-15T11:23:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:build': {}
        'f:spec':
          'f:output':
            'f:to':
              .: {}
              'f:kind': {}
              'f:name': {}
          'f:runPolicy': {}
          'f:source':
            'f:binary': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy':
              .: {}
              'f:from':
                .: {}
                'f:kind': {}
                'f:name': {}
            'f:type': {}
          'f:triggers': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2021-08-15T11:23:38Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:lastVersion': {}
  namespace: trash
  labels:
    build: processing
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'processing:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'openjdk11:latest'
  postCommit: {}
  source:
    type: Binary
    binary: {}
  triggers:
    - type: GitHub
      github:
        secret: x8TCe_BcZCzyJ1KDEhSh
    - type: Generic
      generic:
        secret: 50yiKdbonbkcG-UFPWMd
  runPolicy: Serial
status:
  lastVersion: 1
