kind: Deployment
apiVersion: apps/v1
metadata:
    name: processing
    labels:
        app: processing
spec:
    replicas: 1
    selector:
        matchLabels:
            app: processing
    template:
        metadata:
            annotations:
                sidecar.istio.io/inject: 'true'
            labels:
                app: processing
        spec:
            containers:
                -   name: processing
                    image: 'processing:latest'
                    imagePullPolicy: IfNotPresent
                    ports:
                        -   containerPort: 8080
