kind: Deployment
apiVersion: apps/v1
metadata:
    name: countries
    namespace: default
    labels:
        app: countries
spec:
    replicas: 1
    selector:
        matchLabels:
            app: countries
    template:
        metadata:
            annotations:
                sidecar.istio.io/inject: 'true'
            labels:
                app: countries
        spec:
            containers:
                -   name: countries
                    image: 'countries:latest'
                    imagePullPolicy: Never
                    ports:
                        -   containerPort: 8080
                    resources:
                        limits:
                            cpu: 300m
                            memory: 300Mi
                        requests:
                            cpu: 300m
                            memory: 300Mi
