apiVersion: v1
kind: Service
metadata:
    name: countries
    namespace: default
    labels:
        app: countries
spec:
    type: NodePort
    selector:
        app: countries
    ports:
        - port: 8080
          name: http
          protocol: TCP
